import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Sidebar from "./components/sideBar";
import Provider from "./utils/provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {" "}
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Navbar />
        <div className="flex">
          <Sidebar />
          <Provider>
            <main className="flex-1 bg-gray-50">{children}</main>
          </Provider>
        </div>
      </body>
    </html>
  );
}
